### ISSUE TITLE
Add Meson support in the libxml++-4-0 and master branches

### ISSUE THREAD

**Issue by kjellahl** [libxmlplusplus/libxmlplusplus#19]
The changes that will add Meson support in the libxml++-4-0 and master branches
will be very similar to the changes in the libxml++-3-2 branch. I plan to
push these changes directly, without writing PRs.

@fanc999 When I've pushed these changes, it would be fine if you can check if
more changes are necessary for MSVC builds.

**Comment by kjellahl** [comment]
@fanc999 I have updated the libxml++-4-0 and master branches with Meson build support.
The differences in the Meson build support between the branches are really small.

**Comment by fanc999** [comment]
Hi @kjellahl,

It seems the Visual Studio build support in the Meson build files in the `libxml++-4-0` and `master` branches are ready to go at this point, without needing further changes.

With blessings, and cheers!
