### ISSUE TITLE
Links to documentation are broken

### ISSUE THREAD

**Issue by ntonnaett** [libxmlplusplus/libxmlplusplus#25]
Both links to the reference and the manual on the [github.io page](https://libxmlplusplus.github.io/libxmlplusplus/) are broken or down

**Comment by kjellahl** [comment]
Which links are broken? When I test, both https://developer-old.gnome.org/libxml++-tutorial/
and https://developer-old.gnome.org/libxml++/ can be reached.

**Comment by ntonnaett** [comment]
They are working again here too. Sorry for the noise!
