### ISSUE TITLE
Problem with CI on Windows MSVC

### ISSUE THREAD

**Issue by kjellahl** [libxmlplusplus/libxmlplusplus#64]
After the latest changes in libxml2, the meson-windows-2022.yml CI test fails.

> libLibXml2.a(dict.c.obj) : error LNK2019: unresolved external symbol BCryptGenRandom referenced in function xmlInitRandom

BCryptGenRandom() is called only `#ifdef _WIN32`. The linker does not find it.

@talisein You added the meson-windows-2022.yml CI test. Can you make it work again?
I don't know if the bug is in the CI test file or somewhere else.

**Comment by talisein** [comment]
bcrypt was an added dep a few days ago in xml2.

Looks like the quick fix would be to add bcrypt to https://github.com/libxmlplusplus/libxmlplusplus/blob/master/libxml%2B%2B%2Fmeson.build#L106

I think ideally both winsock and bcrypt deps would be picked up from xml2's cmake.. I'll try and look at that closer before pushing a PR.

Also currently we're grabbing xml2 master, I wonder if we should target a particular release

**Comment by kjellahl** [comment]
xml2 master or a particular release? There are pros and cons with both.
If we use xml2 master, we have a chance to notice changes in xml2 that affect
xml++ before the changes have entered an xml2 release. On the other hand the
CI test becomes more unstable. It can fail due to temporary xml2 changes that
will never make it into a release, or a new xml2 bug that will soon be fixed.

**Comment by talisein** [comment]
I looked at the meson/cmake generation. Both static and shared have meson report `LINK_LIBRARIES': ['ws2_32', 'bcrypt', 'Threads::Threads']`, but the generated meson.build file for the static version is missing the necessary `link_args : ['ws2_32.lib', 'bcrypt.lib']`. Oddly, the xml2 test executables do have the link_args, and there's no good explanation looking at the CMakeList.txt or the cmake_trace.txt.

I think taking the simple route is most reasonable for now, as I've done in #65. Upstream shouldn't be adding dependencies very often I think...
