### ISSUE TITLE
Feature request: support xpath functions like count

### ISSUE THREAD

**Issue by MariePreusse** [libxmlplusplus/libxmlplusplus#66]
I have a project where I need to use functions defined from xpath 1.0 like count and strings. Here is the definition of count:

> Function: number count(node-set)
> 
> The [count](https://www.w3.org/TR/1999/REC-xpath-19991116/#function-count) function returns the number of nodes in the argument node-set.

when running with xmllint e.g. I can enter on this playlist.xml (http://grantm.github.io/perl-libxml-by-example/_static/xpath-sandbox/xpath-sandbox.html)

`xmllint --xpath "count(//person)" playlist.xml`

and I get the number 18 as a result. 

When using libxml++ I get the error message from nodes/node.cc:88  **Only nodeset result types are supported.**
```

  auto result = xmlXPathEval((const xmlChar*)xpath.c_str(), ctxt);
  if (!result)
  {
    xmlXPathFreeContext(ctxt);
    throw xmlpp::exception("Invalid XPath: " + xpath);
  }

  if (result->type != XPATH_NODESET)
  {
    xmlXPathFreeObject(result);
    xmlXPathFreeContext(ctxt);
    throw xmlpp::internal_error("Only nodeset result types are supported.");
```

Is there a way to use functions that have a result type that is not an xpath nodeset?

**Comment by kjellahl** [comment]
What about `node->eval_to_number("count(//person)")`?

Would you prefer new methods, such as:
```
std::variant<NodeSet,bool,double,ustring> xmlpp::Node::find2(const ustring& xpath, const PrefixNsMap& namespaces = {});
std::variant<const_NodeSet,bool,double,ustring> xmlpp::Node::find2(const ustring& xpath, const PrefixNsMap& namespaces = {}) const;
```
Which version of libxml++ do you use? 2, 3, 4 or 5? libxml++2 and libxml++3 are
old versions. I don't want to add new API in them.

**Comment by MariePreusse** [comment]
Hey kjellahl, thanks for the fast reply!
In my application the xpath expression is entered by the user. So I think `node->eval_to_number("count(//person)")` could be used as a work around, if I pre-check the xpath condition first. In case it starts with / I use `find`, in case it starts with count I use `eval_to_number`. 
But the new methods you proposed would solve the problem much more elegantly. I am currently using libxml++-3_0-1 on openSuse, but I think I can upgrade to libxml++4 or 5.

**Comment by kjellahl** [comment]
The new method is called Node::eval_xpath() instead of find2().
I've added it in libxml++4 and 5, but it may take quite some time before I make new
releases of libxml++. Until then, it's only available if you build libxml++
from the git repo.

If you want to do without Node::eval_path(), a possible workaround might be
something like:
```
xmlpp::XPathResultType result_type = xmlpp::XPathResultType::UNDEFINED;
auto number_val = node->eval_to_number(xpath, &result_type);
switch (result_type)
{
case xmlpp::XPathResultType::NODESET:
  nodeset = node->find(xpath);
  break;
case xmlpp::XPathResultType::BOOLEAN:
  bool_val = node->eval_to_boolean(xpath);
  break;
case xmlpp::XPathResultType::NUMBER:
  break;
case xmlpp::XPathResultType::STRING:
  string_val = node->eval_to_string(xpath);
  break;
}
```
It's not optimal. In most cases the XPath is evaluated twice.

**Comment by MariePreusse** [comment]
That's great! Thank you so much kjellahl, it's amazing how fast I got a solution for my project here. I will give the workaround a try until the next release is out. 
Best regards and many thanks
Marie
