### ISSUE TITLE
libxml++-4: Use glibmm-2.66 instead of glibmm-2.64

### ISSUE THREAD

**Issue by kjellahl** [libxmlplusplus/libxmlplusplus#7]
The ABI name of the unstable glibmm has been increased once again.
The libxml++-4-0 branch should be updated with the attached patch.

[0001-Use-glibmm-2.66-instead-of-glibmm-2.64.txt](https://github.com/libxmlplusplus/libxmlplusplus/files/4347867/0001-Use-glibmm-2.66-instead-of-glibmm-2.64.txt)

I don't seem to have write permission to github.com/libxmlplusplus/libxmlplusplus.
```
ERROR: Permission to libxmlplusplus/libxmlplusplus.git denied to kjellahl.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
@murraycu Can you push the patch or give me write permission, please.

It's not important that I have write permission. I don't expect to work with
libxml++ in the future. I've enough to do with gtkmm and its dependencies.

**Comment by murraycu** [comment]
Thanks. I've invited you via github.

**Comment by kjellahl** [comment]
Thanks. Now I can push to libxmlplusplus. I've pushed the patch that fixes this issue.
